### ISSUE TITLE
根据权限配置路由

### ISSUE THREAD

**Issue by gusucity** [YutHelloWorld/vortex-react#21]
您好。刚开始学redux。很喜欢您这套脚手架。让我熟悉了redux的数据流是如何工作的。感谢您的帮助。

在这儿冒昧的向您请教一下。如果要做权限配置。根据是否登录分配路由访问权限。显示不同内容(登录状态和非登录状态)。应该如何配置layout和router。？

**Comment by YutHelloWorld** [comment]
可以参看这个官方示例： https://reacttraining.com/react-router/web/example/auth-workflow 。

**Comment by gusucity** [comment]
好的。谢谢。我去试试。
