### ISSUE TITLE
Description in English

### ISSUE THREAD

**Issue by ronal2do** [YutHelloWorld/vortex-react#29]
The project is apparently excellent, but I would like to read more about it in the documentation.

I wonder if you think about putting SSR.

**Comment by YutHelloWorld** [comment]
Hey! I'm glad that someone would like this project:) 

Regrettably, we did not have SSR app, and we will add english document and SSR to our todo list.
Our todo list:

- [ ] English document
- [ ] A version using Mobx
- [ ] Unit tests（mocha?）
- [ ] SSR

**Comment by ronal2do** [comment]
Greater man! 

I would love to help with this project.

**Comment by YutHelloWorld** [comment]
Welcome PR!

I compeleted the version using mobx just now. I think mobx is a good choice for little project.

And next work is writing a english documentation 🤠

**Comment by YutHelloWorld** [comment]
Mobx boilerplate: https://github.com/YutHelloWorld/react-mobx-starter-kit
