### ISSUE TITLE
用react-loadable分割代码，不用在webpack配置里面设置分离代码吗？

### ISSUE THREAD

**Issue by liubin915249126** [YutHelloWorld/vortex-react#42]
不用在webpack.config.js里面设置output.chunkfilename吗？

**Comment by YutHelloWorld** [comment]
https://github.com/YutHelloWorld/vortex-react/blob/master/src/routes/CustomHome.js#L13
webpack的魔法注释来命名chunckfile名称，你可以在加载的时候控制台的network里看到分割的chunck名称

**Comment by liubin915249126** [comment]
thanks
